### ISSUE TITLE
Cocoapods integration

### ISSUE THREAD

**Issue by chrux** [honghaoz/Loggerithm#1]
I am trying to use this with XCode 6.2 and Cocoapods 0.36.0 with no success, any idea how to make this works, I am importing the using
`import ZHSwiftLogger`

but the methods are not detected.

**Comment by chrux** [comment]
Ok, the answer is here https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/AccessControl.html#//apple_ref/doc/uid/TP40014097-CH41-ID7, all elements has a _internal_ visibility, we need to explicitly specify to be pubilc.

**Comment by honghaoz** [comment]
@chrux Hi chrux, all of these methods are exposed to the whole project using it. If you want to use `import ZHSwiftLogger`
Then I think git submodule will be for this.
For the cocoa pods integration, I will add a spec as soon as I can, possibly by Friday.
If you like, you can help me to create one, make a PR, :)

**Comment by honghaoz** [comment]
@chrux Seems like the pod spec file cannot pass the validation of pod lint, for now, if you like, just drag the file into the project. I'll fix it later

**Comment by honghaoz** [comment]
@chrux I'm

**Comment by honghaoz** [comment]
@chrux Hey, `ZHSwiftLogger` has been renamed to `Loggerithm`, which is also CocoaPod supported. 
You can use `pod 'Loggerithm', '~> 1.1'` to install it. Please check README. Thanks!

**Comment by honghaoz** [comment]
@chrux Now you can use `pod 'Loggerithm', '~> 1.2'`

**Comment by chrux** [comment]
thanks @honghaoz, I will test it.
