### ISSUE TITLE
DEBUG mode for Release configuration

### ISSUE THREAD

**Issue by Latyntsev** [honghaoz/Loggerithm#11]
Hi

There is problems with cocoapod specs.
when i add this dependency. DEBUG flag was added to release configuration as well.

In pod spec you have line
`"OTHER_SWIFT_FLAGS": "-D DEBUG"`

i guess it should be 
`"OTHER_SWIFT_FLAGS[config=Debug]": "-D DEBUG"`

**Comment by honghaoz** [comment]
Hi @Latyntsev, sorry for my fault.

I've tried that config in https://github.com/honghaoz/Loggerithm/commit/ac4fbd02b83fa7ed5a99442d7a75e27b4e94e7f2

but seems like it didn't work as my expected.

Anyway, I've removed that flag in pod spec and updated to 1.3.2.

Try up update your pods with `pod 'Loggerithm', '~> 1.3'`.

Thanks

**Comment by Latyntsev** [comment]
@honghaoz, cool, thank you very much
