### ISSUE TITLE
No output in XCode after installing

### ISSUE THREAD

**Issue by sola92** [honghaoz/Loggerithm#12]
Just installed version 1.3.2.. the cocoapods install was successful. And I specified the DEBUG swift compiler but I don't see any output in XCode.

Please let me know if you need any more info from me.

**Comment by honghaoz** [comment]
@sola92 Hi, I will look into this. Btw, are you using Swift 3?

**Comment by sola92** [comment]
No, I'm running swift 2.

**Comment by honghaoz** [comment]
@sola92 Can you try `print` or `NSLog`? Loggerithm is just using `print` or `NSLog` to log. btw, are you running Xcode7.3.1?

**Comment by sola92** [comment]
print and NSLog work. Yes I am.

**Comment by honghaoz** [comment]
@sola92 Can you send me a demo project. Because on my side, It works for Swift 2.2 in Xcode 7.3
