### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [honghaoz/Loggerithm#13]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by honghaoz** [comment]
@lfarah Hi, I'm working on it now. Will push it asap!

**Comment by mxie1563** [comment]
The current module works in Swift 3 ( for me at least ) with a lot of compile warnings.

**Comment by arturgrigor** [comment]
There's a [PR](https://github.com/honghaoz/Loggerithm/pull/14) for this. If you don't want to wait for it to be accepted you can use this [fork](https://github.com/arturgrigor/Loggerithm).

**Comment by honghaoz** [comment]
Sorry I missed this issue. Great thanks to @arturgrigor !
