### ISSUE TITLE
Support OS X

### ISSUE THREAD

**Issue by kylef** [honghaoz/Loggerithm#2]
I don't see any reason why this needs a dependency on UIKit.

**Comment by honghaoz** [comment]
This needs to be updated for OSX, will do soon. The reasons why it needs UIKit for now is because it uses UIColor for color customization.

**Comment by honghaoz** [comment]
@kylef Hey, It's has been update to 1.1, which supports OSX. 
You can use `pod 'Loggerithm', '~> 1.1'`.

**Comment by honghaoz** [comment]
@kylef Now you can use `pod 'Loggerithm', '~> 1.2'`

**Comment by honghaoz** [comment]
Loggerithm has been tested in a sample Cocoa project. This issue could be closed
