### ISSUE TITLE
Inaccurate info in the Readme.

### ISSUE THREAD

**Issue by DaveWoodCom** [honghaoz/Loggerithm#3]
The Readme states XCGLogger only uses `println()` and doesn't use `NSLog()`. This is inaccurate. NSLog support was added as an option using the `XCGNSLogDestination` class.

**Comment by honghaoz** [comment]
@DaveWoodCom Hi Dave, sorry for that obsoleted description. I've modified the README. Thanks for your issue, and it's great to know you are also living in Canada :smiley:
