### ISSUE TITLE
Loggerithm not working on iOS7

### ISSUE THREAD

**Issue by MatthieuTnsc** [honghaoz/Loggerithm#4]
Hi, I'm trying to install Loggerithm via CocoaPods but I get the following error when I run 'pod install'

```
Updating local specs repositories
Analyzing dependencies
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
[!] Unable to satisfy the following requirements:

- `Loggerithm` required by `Podfile`
```

I'm running on OS X El Capitan 10.11 (15A244d) & Xcode 6.4 (6E35b)
I am using CocoaPods with many other dependencies and never get that issue.

Here is the most relevant information I fond about this issue : http://stackoverflow.com/questions/31778963/dyld-warnings-from-using-cocoapods

The thing is that I don't have any problem with these pods : 
- pod 'Parse'
- pod 'Appirater'
- pod 'KVNProgress'
- pod 'MaterialKit'
- pod 'YLMoment'

**Comment by honghaoz** [comment]
Seems like you have tried to use Xcode 7 beta? Not sure whether this command helps
`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer/`

**Comment by MatthieuTnsc** [comment]
Yes I tried it but it is uninstalled since a while and I reinstalled Cocoapods and Xcode Tools since.
I just tried your command and still got the same error.

**Comment by honghaoz** [comment]
Hmm, I also have no clues. Since El Capitan is still in beta, not sure about it. 
Can you post your pod file?

**Comment by MatthieuTnsc** [comment]
Here it is : 

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
use_frameworks!

pod 'Parse'
pod 'Appirater'
pod 'KVNProgress'
pod 'MaterialKit'
pod 'YLMoment', '~> 0.2.0'
pod 'Loggerithm', '~> 1.2'
```

**Comment by honghaoz** [comment]
Ohh, wait, the platform is for 7.0, Loggerithm is specifying 8.0. That's probably why it doesn't work.

**Comment by honghaoz** [comment]
I should update it for iOS7, but since I don't have a platform to test it. So I just used `s.ios.deployment_target = "8.0"` in the pod spec file.

[Loggerithm.podspec](https://github.com/honghaoz/Loggerithm/blob/master/Loggerithm.podspec). 

If you have iOS7 devices, you can help me to test it.
- Fork this project. 
- Modify Loggerithm.podspec file:
  - Change the `s.ios.deployment_target` to `7.0`
  - Set `s.source           = { : path => "<path of pod spec>"}`
- Run `pod install` locally to see how it works

**Comment by MatthieuTnsc** [comment]
Thanks, it works with iOS 8.0 as target.
dyld: warnings still prompting but doesn't affect the process apparently !

I wanted to use Loggerithm into my app but I really need to keep supporting iOS 7.0 so I hope you'll be supporting it one day :)

**Comment by honghaoz** [comment]
@MatthieuTnsc Let me create a branch for iOS7, will let you know how it works

**Comment by honghaoz** [comment]
@MatthieuTnsc Can you try `pod 'Loggerithm', :git => 'https://github.com/honghaoz/Loggerithm.git', :branch => 'test-ios7'`

If it works, I'll update the master branch

**Comment by MatthieuTnsc** [comment]
Done! pod install is working from this branch with iOS 7 targeted.
I'll play with it and tell you if I encounter some issues. Thank you for all your work and reactivity :+1:

**Comment by honghaoz** [comment]
@MatthieuTnsc Thanks man! If everything works well. I can update it to main pod spec.

**Comment by honghaoz** [comment]
@MatthieuTnsc Hey, I found this issue https://github.com/CocoaPods/swift/issues/22.
I think even though with `test-ios7`, you can use cocoa pods to install `Loggerithm`, but the App maybe rejected by Apple. A better way to use `Loggerithm` with CocoaPods on iOS7 will be installing it manually.
