### ISSUE TITLE
pod install faild

### ISSUE THREAD

**Issue by dabing1022** [honghaoz/Loggerithm#6]
I use command `pod install` to install Loggerithm as Readme says, but the console logs `Unable to find a pod with name matching`Loggerithm'`. It seems something wrong happend to Loggerithm with cocoapods.

**Comment by honghaoz** [comment]
Can you show me your podfile? Or you can try `pod try Loggerithm` to see whether it works on your computer

**Comment by dabing1022** [comment]
My pod file as beblow:

``` c
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'Loggerithm', '~> 1.2'
```

Maybe I need reinstall my cocoapods in my computer.

**Comment by honghaoz** [comment]
@dabing1022 Hey, your pod file looks good. Have you tried to install other pods? I'm not sure about your network accessibility to `'https://github.com/CocoaPods/Specs.git'`. Anyway, let me know how it works now

**Comment by dabing1022** [comment]
Sorry to feed back later. After I reinstall my cocoapods, everythings looks well. Many thanks.

**Comment by honghaoz** [comment]
@dabing1022 No problems
